trigger: none  # Aucun déclencheur automatique

stages:
- stage: Deploy
  displayName: 'CD - Login and Deploy to AKS'
  jobs:
    - job: DeployToAKS
      displayName: 'Deploy to AKS'
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - checkout: self
          displayName: 'Checkout repository files'

        - task: Kubernetes@1
          displayName: 'Login to AKS'
          inputs:
            connectionType: 'Azure Resource Manager'
            azureSubscriptionEndpoint: 'aks'  # Vérifie que ce nom existe dans "Service Connections"
            azureResourceGroup: 'k8sgroupe'
            kubernetesCluster: 'k8scluster'
            command: 'login'

        - script: |
            echo "🚀 Deploying app to AKS..."
            kubectl apply -f k8s-deployment.yaml

            echo "🌐 Getting public IP address:"
            kubectl get svc angular-service -o jsonpath="{.status.loadBalancer.ingress[0].ip}" || echo "Service not yet ready"
          displayName: 'Deploy app and get public IP'
